#!/usr/bin/env python3
"""
NWN MDL Viewer — Build Script
Assembles all source files into a single distributable dist/index.html.

Usage:
  python build.py          → produces dist/index.html
  python build.py --watch  → rebuilds on file change (requires 'watchdog')

WASM Handling:
  - dist/wasm/cleanmodels.wasm  is copied for GitHub Pages (HTTP mode).
  - js/cleanmodels_wasm.js (Base64) is embedded into the standalone HTML
    so that file:// mode works without a server. The file must be present
    for this — it is generated by the update-wasm.yml workflow.

Three.js Handling (see docs/THREEJS_UPGRADE.md):
  - Upstream dropped the classic/UMD build after r160, so Three.js is loaded
    as an ES module by js/three-loader.js, which bridges it back onto the
    global window.THREE and then injects the viewer's own script files.
  - js/three-loader.js is always inlined (same treatment as wasm_exec.js).
  - js/three_module_b64.js (Base64 copy of vendor/three/three.module.min.js)
    is embedded ahead of it, same optional-with-warning treatment as the WASM
    Base64 above — it is what lets the loader's file:// branch work without a
    server. Generated by update-three-vendor.yml.
  - dist/vendor/three/ is still copied (see step 9): the loader's HTTP(S)
    branch does a real import() of vendor/three/three.module.min.js when the
    built HTML is served over a server (GitHub Pages), not opened directly.
"""

import os
import re
import sys
import shutil
from pathlib import Path

ROOT   = Path(__file__).parent
DIST   = ROOT / 'dist'
SRC    = ROOT / 'index.html'
CSS    = ROOT / 'css' / 'viewer.css'
JS_DIR = ROOT / 'js'
WASM_DIR      = ROOT / 'wasm'
WASM_B64_FILE = JS_DIR / 'cleanmodels_wasm.js'   # Base64 bundle for file:// mode

# NEW: Three.js ES-module loader — see docs/THREEJS_UPGRADE.md
THREE_LOADER_FILE = JS_DIR / 'three-loader.js'       # always required, always inlined
THREE_B64_FILE    = JS_DIR / 'three_module_b64.js'   # optional, Base64 bundle for file:// mode
NWN_SCRIPT_TYPE    = 'text/nwn-script'               # marks the 25 viewer files as inert in the DOM;
                                                      # js/three-loader.js reads and runs them itself

def read(path):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f'Required file not found: {p}')
    return p.read_text(encoding='utf-8')

def extract_js_order(html: str) -> list[str]:
    """
    Reads the JS file order directly from index.html.
    Captures all <script [type="text/nwn-script"] src="js/..."> tags between
    the '<!-- NWN MDL Viewer — Module -->' comment and </body>. The type
    attribute is optional in the regex so this still matches if that
    convention ever changes again.
    """
    section_match = re.search(
        r'<!-- NWN MDL Viewer — Module -->(.*?)</body>',
        html,
        re.DOTALL
    )
    if not section_match:
        raise ValueError(
            'Marker "<!-- NWN MDL Viewer — Module -->" not found in index.html.'
        )

    section = section_match.group(1)
    files = re.findall(r'<script\s+(?:type="' + NWN_SCRIPT_TYPE + r'"\s+)?src="js/([^"]+\.js)"', section)

    if not files:
        raise ValueError(
            'No <script src="js/..."> tags found after the module marker.'
        )

    return files


def build(version: str = ''):
    DIST.mkdir(exist_ok=True)

    html = read(SRC)

    # ── 0. Derive JS order from HTML ─────────────────────────────────────────
    js_order = extract_js_order(html)
    print(f'  JS files ({len(js_order)}): {", ".join(js_order)}')

    # ── 0.5. Inject version string ────────────────────────────────────────────
    # index.html contains the placeholder {{APP_VERSION}}.
    # For a local build without --version, the element remains empty (CSS: display:none).
    html = html.replace('{{APP_VERSION}}', version)
    if version:
        print(f'  Version: {version}')

    # ── 1. Inline CSS ─────────────────────────────────────────────────────────
    css_content = read(CSS)
    html = html.replace(
        '<link rel="stylesheet" href="css/viewer.css">',
        f'<style>\n{css_content}\n</style>'
    )

    # ── 2. WASM Base64 for standalone HTML (file:// mode) ────────────────────
    # cleanmodels_wasm.js defines CM_WASM_B64. If it is embedded before
    # cleanmodels.js, the variable is already available and the dynamic
    # script load in cleanmodels.js will be skipped.
    wasm_b64_content = None
    if WASM_B64_FILE.exists():
        wasm_b64_content = read(WASM_B64_FILE)
        size_mb = WASM_B64_FILE.stat().st_size / 1048576
        print(f'  WASM Base64: {WASM_B64_FILE.name} ({size_mb:.1f} MB) — embedding')
    else:
        print(f'  WARNING: {WASM_B64_FILE} not found.')
        print(f'           Standalone HTML will not support file:// mode for binary MDLs.')
        print(f'           → Run workflow update-wasm.yml or call generate_wasm_b64.sh.')

    # ── 2.5 NEW: Three.js ESM Base64 for standalone HTML (file:// mode) ──────
    # Same reasoning and same optional/warn treatment as the WASM Base64 above.
    # three_module_b64.js defines THREE_MODULE_B64; three-loader.js skips its
    # own script-tag fetch of that file when the variable already exists.
    three_b64_content = None
    if THREE_B64_FILE.exists():
        three_b64_content = read(THREE_B64_FILE)
        size_mb = THREE_B64_FILE.stat().st_size / 1048576
        print(f'  Three.js Base64: {THREE_B64_FILE.name} ({size_mb:.1f} MB) — embedding')
    else:
        print(f'  WARNING: {THREE_B64_FILE} not found.')
        print(f'           Standalone HTML will not support file:// mode at all')
        print(f'           (Three.js itself will fail to load — see docs/THREEJS_UPGRADE.md).')
        print(f'           → Run workflow update-three-vendor.yml (workflow_dispatch, force: true).')

    # ── 2.6 NEW: Inline the Three.js loader ───────────────────────────────────
    # js/three-loader.js is always required (unlike the two optional Base64
    # bundles above) — read() raises loudly if it's missing. Embedding the
    # Base64 constant directly ahead of it, in the same <script> block, mirrors
    # step 2's WASM pattern exactly: by the time the loader's IIFE runs,
    # THREE_MODULE_B64 is already a defined global if it was embedded.
    loader_parts = []
    if three_b64_content:
        loader_parts.append(f'// ═══ three_module_b64.js (embedded) ═══\n{three_b64_content}')
    loader_parts.append(f'// ═══ three-loader.js ═══\n{read(THREE_LOADER_FILE)}')
    loader_combined = '\n\n'.join(loader_parts)

    old_loader_tag = '<script src="js/three-loader.js"></script>'
    if old_loader_tag not in html:
        raise ValueError(
            f'"{old_loader_tag}" not found in index.html — '
            'has the Three.js loading block changed? See docs/THREEJS_UPGRADE.md.'
        )
    html = html.replace(old_loader_tag, f'<script>\n{loader_combined}\n</script>', 1)

    # ── 3. Inline all JS files ────────────────────────────────────────────────
    # NEW: emitted as a single inert <script type="text/nwn-script"> tag
    # instead of a directly-executing <script> — js/three-loader.js (inlined
    # above) queries the DOM for this tag and injects its content via a Blob
    # URL once window.THREE is ready, exactly as it does for the 25 separate
    # <script type="text/nwn-script" src="..."> tags in the non-built
    # index.html. Content and order are unchanged; only the wrapping tag is.
    js_parts = []
    for f in js_order:
        if f == 'cleanmodels.js' and wasm_b64_content:
            # Embed Base64 bundle directly before cleanmodels.js
            js_parts.append(f'// ═══ cleanmodels_wasm.js (embedded) ═══\n{wasm_b64_content}')
        js_parts.append(f'// ═══ {f} ═══\n{read(JS_DIR / f)}')

    js_combined = '\n\n'.join(js_parts)
    replacement = f'<script type="{NWN_SCRIPT_TYPE}">\n{js_combined}\n</script>'
    html = re.sub(
        r'<!-- NWN MDL Viewer — Module -->.*?(?=\s*</body>)',
        lambda m: replacement,
        html,
        flags=re.DOTALL
    )

    # ── 4. Write standalone HTML ──────────────────────────────────────────────
    out = DIST / 'index.html'
    out.write_text(html, encoding='utf-8')
    size_kb = out.stat().st_size // 1024
    print(f'✓  Built: dist/index.html  ({size_kb} KB)')

    # ── 5. Copy lang/ for GitHub Pages ───────────────────────────────────────
    lang_src = ROOT / 'lang'
    lang_dst = DIST / 'lang'
    if lang_dst.exists():
        shutil.rmtree(lang_dst)
    shutil.copytree(lang_src, lang_dst)
    print(f'✓  Copied: lang/ → dist/lang/')

    # ── 6. Copy wasm/ for GitHub Pages (HTTP mode) ───────────────────────────
    # In HTTP mode, cleanmodels.js fetches the .wasm via fetch() — for this
    # dist/wasm/cleanmodels.wasm must be present.
    wasm_dst = DIST / 'wasm'
    if wasm_dst.exists():
        shutil.rmtree(wasm_dst)
    if WASM_DIR.exists():
        shutil.copytree(WASM_DIR, wasm_dst)
        wasm_file = wasm_dst / 'cleanmodels.wasm'
        if wasm_file.exists():
            size_mb = wasm_file.stat().st_size / 1048576
            print(f'✓  Copied: wasm/ → dist/wasm/  (cleanmodels.wasm: {size_mb:.1f} MB)')
        else:
            print(f'  WARNING: wasm/cleanmodels.wasm missing — HTTP mode will not work.')
    else:
        print(f'  WARNING: wasm/ directory not found — HTTP mode will not work.')

    # ── 7. Copy favicon ──────────────────────────────────────────────────────
    favicon_src = ROOT / 'favicon.png'
    if favicon_src.exists():
        shutil.copy(favicon_src, DIST / 'favicon.png')
        print(f'✓  Copied: favicon.png → dist/favicon.png')
    else:
        print(f'  WARNING: favicon.png not found — skipping.')
  
    # ── 8. Copy vendor/ (Three.js + fonts) ───────────────────────────────────
    # index.html references vendor/fonts/fonts.css via a relative <link> that
    # step 1 above doesn't touch, so dist/vendor/fonts/ must exist on disk in
    # both HTTP and file:// mode.
    # FIX: the old comment here said Three.js "sits outside" the inlining and
    # is therefore not inlined at all — no longer true. vendor/three/ is still
    # copied, but for a narrower reason now: js/three-loader.js's HTTP(S)
    # branch does a real import() of vendor/three/three.module.min.js at
    # runtime, so dist/vendor/three/ must exist for the GitHub-Pages-over-HTTP
    # case. The file:// case does not touch disk at all — three-loader.js
    # (inlined in step 2.6) carries the ESM build embedded as Base64 instead.
    # vendor/three/three.min.js (the old UMD build) is copied along with
    # everything else in this directory; nothing in the new architecture reads
    # it, but docs/THREEJS_UPGRADE.md §10 keeps it in place on purpose as the
    # rollback target until Phase 2c/2d is verified on all three surfaces.
    vendor_src = ROOT / 'vendor'
    vendor_dst = DIST / 'vendor'
    if vendor_dst.exists():
        shutil.rmtree(vendor_dst)
    if vendor_src.exists():
        shutil.copytree(vendor_src, vendor_dst)
        print(f'✓  Copied: vendor/ → dist/vendor/')
    else:
        print(f'  WARNING: vendor/ directory not found — Three.js/fonts will fail to load in dist/index.html.')

    return out


if __name__ == '__main__':
    # --version vX.Y.Z  → inserted into the HTML placeholder {{APP_VERSION}}
    version = ''
    argv = sys.argv[1:]
    if '--version' in argv:
        i = argv.index('--version')
        if i + 1 < len(argv):
            version = argv[i + 1]

    if '--watch' in argv:
        try:
            from watchdog.observers import Observer
            from watchdog.events import FileSystemEventHandler
            import time

            class Handler(FileSystemEventHandler):
                def on_modified(self, event):
                    # Ignore changes in the dist/ output directory,
                    # otherwise, every build triggers another build.
                    if str(Path(event.src_path)).startswith(str(DIST)):
                        return
                    if event.src_path.endswith(('.html', '.css', '.js', '.json')):
                        print(f'  Changed: {event.src_path}')
                        try:
                            build(version=version)
                        except Exception as e:
                            print(f'  Build error: {e}')

            observer = Observer()
            observer.schedule(Handler(), str(ROOT), recursive=True)
            observer.start()
            print('Watching for changes… (Ctrl+C to stop)')
            build(version=version)
            try:
                while True:
                    time.sleep(1)
            except KeyboardInterrupt:
                observer.stop()
            observer.join()
        except ImportError:
            print('watchdog not installed. Run: pip install watchdog')
            sys.exit(1)
    else:
        build(version=version)
