#!/usr/bin/env python3
"""
NWN MDL Viewer — Build Script
Assembles all source files into a single distributable dist/index.html.

Usage:
  python build.py          → produces dist/index.html
  python build.py --watch  → rebuilds on file change (requires 'watchdog')

WASM Handling:
  - dist/wasm/cleanmodels.wasm  is copied for GitHub Pages (HTTP mode).
  - js/cleanmodels_wasm.js (Base64) is embedded into the standalone HTML
    so that file:// mode works without a server. The file must be present
    for this — it is generated by the update-wasm.yml workflow.
"""

import os
import re
import sys
import shutil
from pathlib import Path

ROOT   = Path(__file__).parent
DIST   = ROOT / 'dist'
SRC    = ROOT / 'index.html'
CSS    = ROOT / 'css' / 'viewer.css'
JS_DIR = ROOT / 'js'
WASM_DIR      = ROOT / 'wasm'
WASM_B64_FILE = JS_DIR / 'cleanmodels_wasm.js'   # Base64 bundle for file:// mode

def read(path):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f'Required file not found: {p}')
    return p.read_text(encoding='utf-8')

def extract_js_order(html: str) -> list[str]:
    """
    Reads the JS file order directly from index.html.
    Captures all <script src="js/..."> tags between the
    '<!-- NWN MDL Viewer — Module -->' comment and </body>.
    """
    section_match = re.search(
        r'<!-- NWN MDL Viewer — Module -->(.*?)</body>',
        html,
        re.DOTALL
    )
    if not section_match:
        raise ValueError(
            'Marker "<!-- NWN MDL Viewer — Module -->" not found in index.html.'
        )

    section = section_match.group(1)
    files = re.findall(r'<script\s+src="js/([^"]+\.js)"', section)

    if not files:
        raise ValueError(
            'No <script src="js/..."> tags found after the module marker.'
        )

    return files


def build(version: str = ''):
    DIST.mkdir(exist_ok=True)

    html = read(SRC)

    # ── 0. Derive JS order from HTML ─────────────────────────────────────────
    js_order = extract_js_order(html)
    print(f'  JS files ({len(js_order)}): {", ".join(js_order)}')

    # ── 0.5. Inject version string ────────────────────────────────────────────
    # index.html enthält den Platzhalter {{APP_VERSION}}.
    # Bei lokalem Build ohne --version bleibt das Element leer (CSS: display:none).
    html = html.replace('{{APP_VERSION}}', version)
    if version:
        print(f'  Version: {version}')

    # ── 1. Inline CSS ─────────────────────────────────────────────────────────
    css_content = read(CSS)
    html = html.replace(
        '<link rel="stylesheet" href="css/viewer.css">',
        f'<style>\n{css_content}\n</style>'
    )

    # ── 2. WASM Base64 for standalone HTML (file:// mode) ────────────────────
    # cleanmodels_wasm.js defines CM_WASM_B64. If it is embedded before
    # cleanmodels.js, the variable is already available and the dynamic
    # script load in cleanmodels.js will be skipped.
    wasm_b64_content = None
    if WASM_B64_FILE.exists():
        wasm_b64_content = read(WASM_B64_FILE)
        size_mb = WASM_B64_FILE.stat().st_size / 1048576
        print(f'  WASM Base64: {WASM_B64_FILE.name} ({size_mb:.1f} MB) — embedding')
    else:
        print(f'  WARNING: {WASM_B64_FILE} not found.')
        print(f'           Standalone HTML will not support file:// mode for binary MDLs.')
        print(f'           → Run workflow update-wasm.yml or call generate_wasm_b64.sh.')

    # ── 3. Inline all JS files ────────────────────────────────────────────────
    js_parts = []
    for f in js_order:
        if f == 'cleanmodels.js' and wasm_b64_content:
            # Embed Base64 bundle directly before cleanmodels.js
            js_parts.append(f'// ═══ cleanmodels_wasm.js (embedded) ═══\n{wasm_b64_content}')
        js_parts.append(f'// ═══ {f} ═══\n{read(JS_DIR / f)}')

    js_combined = '\n\n'.join(js_parts)
    replacement = f'<script>\n{js_combined}\n</script>'
    html = re.sub(
        r'<!-- NWN MDL Viewer — Module -->.*?(?=\s*</body>)',
        lambda m: replacement,
        html,
        flags=re.DOTALL
    )

    # ── 4. Write standalone HTML ──────────────────────────────────────────────
    out = DIST / 'index.html'
    out.write_text(html, encoding='utf-8')
    size_kb = out.stat().st_size // 1024
    print(f'✓  Built: dist/index.html  ({size_kb} KB)')

    # ── 5. Copy lang/ for GitHub Pages ───────────────────────────────────────
    lang_src = ROOT / 'lang'
    lang_dst = DIST / 'lang'
    if lang_dst.exists():
        shutil.rmtree(lang_dst)
    shutil.copytree(lang_src, lang_dst)
    print(f'✓  Copied: lang/ → dist/lang/')

    # ── 6. Copy wasm/ for GitHub Pages (HTTP mode) ───────────────────────────
    # In HTTP mode, cleanmodels.js fetches the .wasm via fetch() — for this
    # dist/wasm/cleanmodels.wasm must be present.
    wasm_dst = DIST / 'wasm'
    if wasm_dst.exists():
        shutil.rmtree(wasm_dst)
    if WASM_DIR.exists():
        shutil.copytree(WASM_DIR, wasm_dst)
        wasm_file = wasm_dst / 'cleanmodels.wasm'
        if wasm_file.exists():
            size_mb = wasm_file.stat().st_size / 1048576
            print(f'✓  Copied: wasm/ → dist/wasm/  (cleanmodels.wasm: {size_mb:.1f} MB)')
        else:
            print(f'  WARNING: wasm/cleanmodels.wasm missing — HTTP mode will not work.')
    else:
        print(f'  WARNING: wasm/ directory not found — HTTP mode will not work.')

    return out


if __name__ == '__main__':
    # --version vX.Y.Z  → wird in den HTML-Platzhalter {{APP_VERSION}} eingesetzt
    version = ''
    argv = sys.argv[1:]
    if '--version' in argv:
        i = argv.index('--version')
        if i + 1 < len(argv):
            version = argv[i + 1]

    if '--watch' in argv:
        try:
            from watchdog.observers import Observer
            from watchdog.events import FileSystemEventHandler
            import time

            class Handler(FileSystemEventHandler):
                def on_modified(self, event):
                    # Änderungen im dist/-Ausgabeverzeichnis ignorieren,
                    # sonst löst jeder Build einen weiteren Build aus.
                    if str(Path(event.src_path)).startswith(str(DIST)):
                        return
                    if event.src_path.endswith(('.html', '.css', '.js', '.json')):
                        print(f'  Changed: {event.src_path}')
                        try:
                            build(version=version)
                        except Exception as e:
                            print(f'  Build error: {e}')

            observer = Observer()
            observer.schedule(Handler(), str(ROOT), recursive=True)
            observer.start()
            print('Watching for changes… (Ctrl+C to stop)')
            build(version=version)
            try:
                while True:
                    time.sleep(1)
            except KeyboardInterrupt:
                observer.stop()
            observer.join()
        except ImportError:
            print('watchdog not installed. Run: pip install watchdog')
            sys.exit(1)
    else:
        build(version=version)
